### ISSUE TITLE
Outer par mode error with Quarto 1.4 

### ISSUE THREAD

**Issue by cderv** [quarto-journals/acm#36]
Rendering the template now throws 

````
ERROR: 
compilation failed- error
LaTeX Error: Not in outer par mode.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.728 {
       \centering \includegraphics{sample-franklin.png}}

see template.log for more information.
ERROR: Error
    at renderFiles (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/render-files.ts:346:23)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async render (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/render-shared.ts:99:18)
    at async Command.fn (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/command/render/cmd.ts:248:26)
    at async Command.execute (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/vendor/deno.land/x/cliffy@v0.25.4/command/command.ts:1790:7)
    at async quarto (file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/quarto.ts:155:3)
    at async file:///C:/Users/chris/Documents/DEV_R/quarto-cli/src/quarto.ts:186:5
````

This is reported initially in 
* https://github.com/quarto-dev/quarto-cli/issues/8207

Problem with the extension filter
https://github.com/quarto-journals/acm/blob/72e302d0f24240db1b2c4cd0c16522e61fe424b2/_extensions/quarto-journals/acm/fancy-figure.lua#L52-L73

**Comment by cscheid** [comment]
Yes, I'm aware. (The long, long story is that all of the FloatRefTarget work was inspired by this long-standing ACM figure bug!) I'll fix once we have 1.4 properly out.

**Comment by prashantnag** [comment]
@cscheid any update on this???
